import React, { useState, useEffect } from 'react';

export function App() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetch('/api/v1/items')
      .then(res => res.json())
      .then(d => setData(d.items || []))
      .catch(() => setData([]));
  }, []);

  return (
    <div className="min-h-screen bg-[#0B0D0E] text-white p-8 font-sans">
      <header className="mb-8 border-b border-gray-800 pb-4 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-[#76B900]">KirstonAI Application</h1>
          <p className="text-xs text-gray-400">Generated by KirstonAI Coding Agent (Build simple app)</p>
        </div>
        <span className="px-3 py-1 bg-[#76B900]/20 text-[#76B900] text-xs font-mono rounded-full border border-[#76B900]/40">
          v1.0.0 Ready
        </span>
      </header>

      <main className="max-w-4xl mx-auto space-y-6">
        <div className="p-6 bg-[#15191C] border border-[#76B900]/40 rounded-2xl shadow-xl">
          <h2 className="text-lg font-bold mb-2">Project Features & Architecture</h2>
          <p className="text-sm text-gray-300 mb-4">
            Requirement: "Build simple app"
          </p>
          <div className="grid grid-cols-3 gap-4 font-mono text-xs">
            <div className="p-3 bg-black/40 rounded-xl border border-gray-800">
              <span className="text-[#76B900] font-bold">Frontend</span>
              <p className="text-gray-400 mt-1">React 18 + TypeScript + Vite</p>
            </div>
            <div className="p-3 bg-black/40 rounded-xl border border-gray-800">
              <span className="text-[#76B900] font-bold">Backend</span>
              <p className="text-gray-400 mt-1">Python FastAPI + AsyncIO</p>
            </div>
            <div className="p-3 bg-black/40 rounded-xl border border-gray-800">
              <span className="text-[#76B900] font-bold">Database</span>
              <p className="text-gray-400 mt-1">PostgreSQL + pgvector</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;