import React, { useState, useEffect, useCallback } from 'react';

const GRID = 20;
const INIT_SNAKE = [{ x: 10, y: 10 }, { x: 10, y: 11 }, { x: 10, y: 12 }];
const INIT_DIR = { x: 0, y: -1 };

interface Score { id: string; player: string; score: number; }

export function App() {
  const [snake, setSnake] = useState(INIT_SNAKE);
  const [dir, setDir] = useState(INIT_DIR);
  const [food, setFood] = useState({ x: 5, y: 5 });
  const [score, setScore] = useState(0);
  const [highScore, setHighScore] = useState(0);
  const [gameOver, setGameOver] = useState(false);
  const [paused, setPaused] = useState(false);
  const [leaderboard, setLeaderboard] = useState<Score[]>([]);
  const [playerName, setPlayerName] = useState('');
  const [showSave, setShowSave] = useState(false);

  const fetchLeaderboard = () => {
    fetch('/api/v1/scores').then(r => r.json()).then(d => setLeaderboard(d.scores || []));
  };
  useEffect(() => { fetchLeaderboard(); }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (['ArrowUp','KeyW'].includes(e.code) && dir.y === 0) setDir({ x: 0, y: -1 });
      else if (['ArrowDown','KeyS'].includes(e.code) && dir.y === 0) setDir({ x: 0, y: 1 });
      else if (['ArrowLeft','KeyA'].includes(e.code) && dir.x === 0) setDir({ x: -1, y: 0 });
      else if (['ArrowRight','KeyD'].includes(e.code) && dir.x === 0) setDir({ x: 1, y: 0 });
      else if (e.code === 'Space') setPaused(p => !p);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [dir]);

  useEffect(() => {
    if (gameOver || paused) return;
    const timer = setInterval(() => {
      setSnake(prev => {
        const head = { x: prev[0].x + dir.x, y: prev[0].y + dir.y };
        if (head.x < 0 || head.x >= GRID || head.y < 0 || head.y >= GRID) { setGameOver(true); setShowSave(true); return prev; }
        if (prev.some(s => s.x === head.x && s.y === head.y)) { setGameOver(true); setShowSave(true); return prev; }
        const next = [head, ...prev];
        if (head.x === food.x && head.y === food.y) {
          setScore(s => { const ns = s + 10; if (ns > highScore) setHighScore(ns); return ns; });
          setFood({ x: Math.floor(Math.random() * GRID), y: Math.floor(Math.random() * GRID) });
        } else next.pop();
        return next;
      });
    }, 120);
    return () => clearInterval(timer);
  }, [dir, food, gameOver, paused, highScore]);

  const restart = () => { setSnake(INIT_SNAKE); setDir(INIT_DIR); setFood({ x: 5, y: 5 }); setScore(0); setGameOver(false); setPaused(false); setShowSave(false); };

  const saveScore = async () => {
    if (!playerName.trim() || score === 0) return;
    await fetch('/api/v1/scores', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({player: playerName, score}) });
    fetchLeaderboard();
    setShowSave(false);
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white flex flex-col items-center justify-center p-6 font-sans gap-6">
      <div>
        <h1 className="text-3xl font-extrabold text-green-400 text-center">🐍 Snake</h1>
        <p className="text-xs text-gray-500 text-center font-mono mt-0.5">Generated by KirstonAI</p>
      </div>
      <div className="flex gap-6 items-start">
        {/* Game grid */}
        <div className="relative p-2 bg-gray-900 border border-green-800 rounded-2xl shadow-lg shadow-green-900/20">
          <div className="grid" style={{gridTemplateColumns:`repeat(${GRID},18px)`,gridTemplateRows:`repeat(${GRID},18px)`}}>
            {Array.from({length:GRID*GRID}).map((_,i) => {
              const x = i%GRID, y = Math.floor(i/GRID);
              const isHead = snake[0].x===x && snake[0].y===y;
              const isBody = !isHead && snake.some(s=>s.x===x&&s.y===y);
              const isFood = food.x===x && food.y===y;
              return <div key={i} className={`w-[18px] h-[18px] rounded-sm ${isHead?'bg-green-300':isBody?'bg-green-600':isFood?'bg-red-500 animate-pulse rounded-full':'bg-transparent'}`}/>;
            })}
          </div>
          {gameOver && (
            <div className="absolute inset-0 bg-black/80 rounded-2xl flex flex-col items-center justify-center gap-3">
              <p className="text-red-400 font-extrabold text-xl">GAME OVER</p>
              <p className="text-gray-300 text-sm">Score: <span className="text-green-400 font-bold">{score}</span></p>
              {showSave && (
                <div className="flex gap-2">
                  <input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Your name" className="px-3 py-1.5 bg-gray-800 border border-gray-600 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none w-28"/>
                  <button onClick={saveScore} className="px-3 py-1.5 bg-green-700 hover:bg-green-600 text-white text-xs font-bold rounded-lg">Save</button>
                </div>
              )}
              <button onClick={restart} className="px-5 py-2 bg-green-500 text-black font-bold text-sm rounded-xl">Play Again</button>
            </div>
          )}
        </div>

        {/* Side panel */}
        <div className="flex flex-col gap-3 w-36">
          <div className="p-3 bg-gray-900 border border-gray-800 rounded-xl text-xs font-mono space-y-2">
            <div className="flex justify-between"><span className="text-gray-400">SCORE</span><span className="text-green-400 font-bold">{score}</span></div>
            <div className="flex justify-between"><span className="text-gray-400">BEST</span><span className="text-yellow-400 font-bold">{highScore}</span></div>
          </div>
          <button onClick={()=>setPaused(p=>!p)} disabled={gameOver} className="w-full py-2 bg-gray-800 border border-gray-700 text-xs font-bold rounded-xl disabled:opacity-50">{paused?'Resume':'Pause'}</button>
          <button onClick={restart} className="w-full py-2 bg-green-700 text-white font-extrabold text-xs rounded-xl">Restart</button>
          <div className="p-2 bg-gray-900 rounded-xl text-[10px] text-gray-500 font-mono space-y-0.5">
            <p>Arrow / WASD</p><p>Space: pause</p><p>Food = +10 pts</p>
          </div>
        </div>

        {/* Leaderboard */}
        <div className="w-40">
          <p className="text-xs font-semibold text-gray-400 mb-2">🏆 Top Scores</p>
          {leaderboard.length === 0 ? <p className="text-gray-600 text-xs text-center py-4">No scores yet</p> : (
            <div className="space-y-1">
              {leaderboard.slice(0,10).map((s,i) => (
                <div key={s.id} className="flex justify-between text-xs">
                  <span className="text-gray-500">#{i+1} {s.player}</span>
                  <span className="text-green-400 font-bold">{s.score}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
export default App;
