import React, { useState, useEffect } from 'react';

interface Item {
  id: string;
  name: string;
  status: string;
}

export function App() {
  const [items, setItems] = useState<Item[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/v1/items')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((d) => setItems(d.items || []))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-gray-950 text-white p-8 font-sans">
      <header className="mb-8 border-b border-gray-800 pb-4 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-green-400">Secure Authentication Platform</h1>
          <p className="text-xs text-gray-400 mt-1">Generated by KirstonAI Coding Agent</p>
        </div>
        <span className="px-3 py-1 bg-green-900/40 text-green-400 text-xs font-mono rounded-full border border-green-700">
          v1.0.0 Ready
        </span>
      </header>
      <main className="max-w-4xl mx-auto">
        {loading && (
          <div className="text-center text-gray-400 py-12">Loading...</div>
        )}
        {error && (
          <div className="p-4 rounded-xl bg-red-900/20 border border-red-700 text-red-400 text-sm">
            Error: {error}
          </div>
        )}
        {!loading && !error && (
          <div className="space-y-3">
            {items.length === 0 ? (
              <p className="text-gray-500 text-center py-8">No items found.</p>
            ) : (
              items.map((item) => (
                <div key={item.id} className="p-4 bg-gray-900 border border-gray-800 rounded-xl flex justify-between items-center">
                  <span className="font-medium">{item.name}</span>
                  <span className="text-xs px-2 py-0.5 rounded-full bg-green-900/30 text-green-400 border border-green-800">
                    {item.status}
                  </span>
                </div>
              ))
            )}
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
