from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(
    title="Secure Task & Auth Platform API",
    version="1.0.0",
    description="Backend API generated by KirstonAI Coding Agent"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    id: str
    name: str
    status: str

@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "Secure Task & Auth Platform Backend"}

@app.get("/api/v1/items")
def get_items():
    return {
        "status": "success",
        "items": [
            {"id": "1", "name": "Initial Feature Task", "status": "active"},
            {"id": "2", "name": "Automated Validation", "status": "passed"}
        ]
    }
