from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import uuid

app = FastAPI(
    title="Secure Authentication Platform API",
    version="1.0.0",
    description="Backend API generated by KirstonAI Coding Agent",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── In-memory store (replace with PostgreSQL in production) ──────────────────
_items_db: List[dict] = [
    {"id": "1", "name": "Initial Feature Task", "status": "active"},
    {"id": "2", "name": "Automated Validation", "status": "passed"},
]

class ItemCreate(BaseModel):
    name: str
    status: Optional[str] = "active"

@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "Secure Authentication Platform Backend"}

@app.get("/api/v1/items")
def get_items():
    return {"status": "success", "items": _items_db, "total": len(_items_db)}

@app.post("/api/v1/items", status_code=201)
def create_item(payload: ItemCreate):
    item = {"id": str(uuid.uuid4())[:8], "name": payload.name, "status": payload.status}
    _items_db.append(item)
    return {"status": "success", "item": item}

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: str):
    global _items_db
    original_count = len(_items_db)
    _items_db = [i for i in _items_db if i["id"] != item_id]
    if len(_items_db) == original_count:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"status": "success", "message": "Item deleted"}
