from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List

app = FastAPI(
    title="Classic Snake Game & High Scores Platform API",
    version="1.0.0",
    description="Backend API generated by KirstonAI Coding Agent"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class HighScore(BaseModel):
    player_name: str
    score: int

high_scores_db = [
    {"player_name": "KirstonAI Pro", "score": 250},
    {"player_name": "SnakeMaster", "score": 180}
]

@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "Classic Snake Game & High Scores Platform Backend"}

@app.get("/api/v1/scores")
def get_scores():
    return {"status": "success", "scores": high_scores_db}

@app.post("/api/v1/scores")
def record_score(score_entry: HighScore):
    high_scores_db.append(score_entry.dict())
    return {"status": "success", "message": "Score recorded!"}

@app.get("/api/v1/items")
def get_items():
    return {
        "status": "success",
        "items": [
            {"id": "1", "name": "Initial Feature Task", "status": "active"},
            {"id": "2", "name": "Automated Validation", "status": "passed"}
        ]
    }
