-- Seed Data
INSERT INTO projects (id, name, description)
VALUES ('proj-1', 'Sample Project', 'Generated by KirstonAI Coding Agent')
ON CONFLICT (id) DO NOTHING;

INSERT INTO scores (player_name, score)
VALUES ('KirstonAI Pro', 250), ('SnakeMaster', 180);
