-- Seed Data
INSERT INTO projects (id, name, description)
VALUES ('proj-1', 'Sample Project', 'Generated by KirstonAI Coding Agent')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tasks (id, project_id, title, status)
VALUES ('task-1', 'proj-1', 'Initial Setup Task', 'completed')
ON CONFLICT (id) DO NOTHING;
