import React, { useState, useEffect } from 'react';

interface Resume {
  id: string;
  name: string;
  description: string;
  status: string;
  created_at?: string;
}

export function App() {
  const [items, setItems] = useState<Resume[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ name: '', description: '', status: 'active' });
  const [submitting, setSubmitting] = useState(false);

  const fetchItems = () => {
    setLoading(true);
    fetch('/api/v1/resumes')
      .then(r => r.ok ? r.json() : Promise.reject(`HTTP ${r.status}`))
      .then(d => setItems(d.resumes || []))
      .catch(e => setError(String(e)))
      .finally(() => setLoading(false));
  };
  useEffect(() => { fetchItems(); }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name.trim()) return;
    setSubmitting(true);
    try {
      const res = await fetch('/api/v1/resumes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setForm({ name: '', description: '', status: 'active' });
      fetchItems();
    } catch (e) { setError(String(e)); }
    finally { setSubmitting(false); }
  };

  const deleteItem = async (id: string) => {
    await fetch(`/api/v1/resumes/${id}`, { method: 'DELETE' });
    fetchItems();
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6 font-sans">
      <header className="mb-6 border-b border-gray-800 pb-4">
        <h1 className="text-2xl font-bold text-blue-400">Resumes Manager</h1>
        <p className="text-xs text-gray-500 mt-0.5">Generated by KirstonAI Coding Agent</p>
      </header>
      <div className="max-w-2xl mx-auto">
        {error && <div className="mb-4 p-3 bg-red-900/20 border border-red-700 text-red-400 text-sm rounded-lg">{error}</div>}
        <form onSubmit={handleSubmit} className="mb-6 p-5 bg-gray-900 border border-gray-800 rounded-xl space-y-3">
          <h2 className="text-sm font-semibold text-gray-300">Add Resume</h2>
          <input required value={form.name} onChange={e => setForm({...form, name: e.target.value})} placeholder="Name..." className="w-full p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:border-blue-500"/>
          <textarea value={form.description} onChange={e => setForm({...form, description: e.target.value})} placeholder="Description..." rows={2} className="w-full p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:border-blue-500 resize-none"/>
          <button type="submit" disabled={submitting} className="w-full py-2.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white font-semibold text-sm rounded-lg transition-colors">
            {submitting ? 'Adding...' : `Add Resume`}
          </button>
        </form>
        {loading ? <div className="text-center text-gray-500 py-10">Loading...</div>
          : items.length === 0 ? <div className="text-center text-gray-500 py-10">No resumes yet. Add one above!</div>
          : (
          <div className="space-y-2">
            {items.map(item => (
              <div key={item.id} className="p-4 bg-gray-900 border border-gray-800 rounded-xl flex justify-between items-start gap-3">
                <div>
                  <p className="font-medium text-gray-100">{item.name}</p>
                  {item.description && <p className="text-xs text-gray-400 mt-0.5">{item.description}</p>}
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className="text-xs px-2 py-0.5 rounded-full border border-green-700 text-green-400">{item.status}</span>
                  <button onClick={() => deleteItem(item.id)} className="text-xs text-red-400 hover:text-red-300">Delete</button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
export default App;
