import React, { useState, useEffect, useRef } from 'react';

const GRID_SIZE = 20;
const INITIAL_SNAKE = [
  { x: 10, y: 10 },
  { x: 10, y: 11 },
  { x: 10, y: 12 },
];
const INITIAL_DIRECTION = { x: 0, y: -1 };

export function App() {
  const [snake, setSnake] = useState(INITIAL_SNAKE);
  const [direction, setDirection] = useState(INITIAL_DIRECTION);
  const [food, setFood] = useState({ x: 5, y: 5 });
  const [score, setScore] = useState(0);
  const [highScore, setHighScore] = useState(0);
  const [gameOver, setGameOver] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [leaderboard, setLeaderboard] = useState<any[]>([]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (['ArrowUp', 'KeyW'].includes(e.code) && direction.y === 0) {
        setDirection({ x: 0, y: -1 });
      } else if (['ArrowDown', 'KeyS'].includes(e.code) && direction.y === 0) {
        setDirection({ x: 0, y: 1 });
      } else if (['ArrowLeft', 'KeyA'].includes(e.code) && direction.x === 0) {
        setDirection({ x: -1, y: 0 });
      } else if (['ArrowRight', 'KeyD'].includes(e.code) && direction.x === 0) {
        setDirection({ x: 1, y: 0 });
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [direction]);

  // Game tick interval loop
  useEffect(() => {
    if (gameOver || isPaused) return;

    const moveSnake = () => {
      setSnake((prevSnake) => {
        const head = {
          x: prevSnake[0].x + direction.x,
          y: prevSnake[0].y + direction.y,
        };

        // Wall collision check
        if (head.x < 0 || head.x >= GRID_SIZE || head.y < 0 || head.y >= GRID_SIZE) {
          setGameOver(true);
          return prevSnake;
        }

        // Self collision check
        if (prevSnake.some((segment) => segment.x === head.x && segment.y === head.y)) {
          setGameOver(true);
          return prevSnake;
        }

        const newSnake = [head, ...prevSnake];

        // Food eating check
        if (head.x === food.x && head.y === food.y) {
          setScore((s) => {
            const newScore = s + 10;
            if (newScore > highScore) setHighScore(newScore);
            return newScore;
          });
          setFood({
            x: Math.floor(Math.random() * GRID_SIZE),
            y: Math.floor(Math.random() * GRID_SIZE),
          });
        } else {
          newSnake.pop();
        }

        return newSnake;
      });
    };

    const timer = setInterval(moveSnake, 120);
    return () => clearInterval(timer);
  }, [direction, food, gameOver, isPaused, highScore]);

  const restartGame = () => {
    setSnake(INITIAL_SNAKE);
    setDirection(INITIAL_DIRECTION);
    setFood({ x: 5, y: 5 });
    setScore(0);
    setGameOver(false);
    setIsPaused(false);
  };

  return (
    <div className="min-h-screen bg-[#0B0D0E] text-white p-6 font-sans flex flex-col items-center justify-center">
      <header className="mb-6 text-center space-y-1">
        <h1 className="text-3xl font-extrabold text-[#76B900] tracking-tight">🐍 Classic Snake Game</h1>
        <p className="text-xs text-gray-400 font-mono">Generated by KirstonAI Autonomous Coding Agent</p>
      </header>

      <div className="flex gap-6 items-start max-w-4xl w-full">
        {/* Snake Canvas Grid */}
        <div className="relative p-3 bg-[#15191C] border border-[#76B900]/50 rounded-2xl shadow-2xl">
          <div
            className="grid bg-[#0B0D0E] border border-gray-800 rounded-xl"
            style={{
              gridTemplateColumns: `repeat(${GRID_SIZE}, 18px)`,
              gridTemplateRows: `repeat(${GRID_SIZE}, 18px)`,
            }}
          >
            {Array.from({ length: GRID_SIZE * GRID_SIZE }).map((_, i) => {
              const x = i % GRID_SIZE;
              const y = Math.floor(i / GRID_SIZE);
              const isSnakeHead = snake[0].x === x && snake[0].y === y;
              const isSnakeBody = snake.some((s) => s.x === x && s.y === y);
              const isFood = food.x === x && food.y === y;

              return (
                <div
                  key={i}
                  className={`w-[18px] h-[18px] transition-colors rounded-sm ${
                    isSnakeHead
                      ? 'bg-[#76B900] shadow-glow'
                      : isSnakeBody
                      ? 'bg-[#84cc16]'
                      : isFood
                      ? 'bg-red-500 animate-pulse rounded-full'
                      : 'bg-transparent'
                  }`}
                />
              );
            })}
          </div>

          {gameOver && (
            <div className="absolute inset-0 bg-black/80 backdrop-blur-sm rounded-2xl flex flex-col items-center justify-center space-y-3">
              <h2 className="text-xl font-extrabold text-red-400 font-mono">GAME OVER</h2>
              <p className="text-xs text-gray-300">Final Score: {score}</p>
              <button
                onClick={restartGame}
                className="px-4 py-2 bg-[#76B900] hover:bg-[#84cc16] text-black font-extrabold text-xs rounded-xl shadow-lg transition"
              >
                Play Again
              </button>
            </div>
          )}
        </div>

        {/* Game Stats & Controls Panel */}
        <div className="space-y-4 flex-1">
          <div className="p-4 bg-[#15191C] border border-gray-800 rounded-2xl space-y-3 font-mono">
            <div className="flex justify-between items-center text-xs">
              <span className="text-gray-400">CURRENT SCORE:</span>
              <span className="text-lg font-bold text-[#76B900]">{score}</span>
            </div>
            <div className="flex justify-between items-center text-xs">
              <span className="text-gray-400">HIGH SCORE:</span>
              <span className="text-lg font-bold text-amber-400">{highScore}</span>
            </div>

            <div className="pt-2 border-t border-gray-800 flex gap-2">
              <button
                onClick={() => setIsPaused(!isPaused)}
                className="flex-1 py-2 bg-[#0B0D0E] hover:bg-gray-800 border border-gray-700 text-xs font-bold rounded-xl transition"
              >
                {isPaused ? 'Resume' : 'Pause'}
              </button>
              <button
                onClick={restartGame}
                className="flex-1 py-2 bg-[#76B900] hover:bg-[#84cc16] text-black font-extrabold text-xs rounded-xl transition"
              >
                Restart
              </button>
            </div>
          </div>

          <div className="p-4 bg-[#15191C] border border-gray-800 rounded-2xl space-y-2 text-xs font-mono text-gray-400">
            <h4 className="font-bold text-white uppercase tracking-wider">Controls:</h4>
            <p>• Use <span className="text-[#76B900] font-bold">Arrow Keys</span> or <span className="text-[#76B900] font-bold">W A S D</span> to steer.</p>
            <p>• Eat red apples to grow & earn 10 points.</p>
            <p>• Avoid running into walls or your own tail!</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;