import React, { useState, useEffect } from 'react';

interface Task { id: string; title: string; status: string; priority: string; due_date?: string; assigned_to?: string; }

const STATUS_COLORS: Record<string, string> = { todo: 'text-gray-400 border-gray-600', in_progress: 'text-blue-400 border-blue-700', done: 'text-green-400 border-green-700' };
const PRIORITY_COLORS: Record<string, string> = { low: 'text-gray-400', medium: 'text-yellow-400', high: 'text-red-400' };

export function App() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [filter, setFilter] = useState('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({ title: '', priority: 'medium', due_date: '', assigned_to: '' });

  const fetchTasks = () => {
    setLoading(true);
    const url = filter === 'all' ? '/api/v1/tasks' : `/api/v1/tasks?status=${filter}`;
    fetch(url).then(r => r.json()).then(d => setTasks(d.tasks || [])).catch(e => setError(String(e))).finally(() => setLoading(false));
  };

  useEffect(() => { fetchTasks(); }, [filter]);

  const createTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.title.trim()) return;
    await fetch('/api/v1/tasks', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(form) });
    setForm({ title: '', priority: 'medium', due_date: '', assigned_to: '' });
    fetchTasks();
  };

  const updateStatus = async (id: string, status: string) => {
    await fetch(`/api/v1/tasks/${id}`, { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ status }) });
    fetchTasks();
  };

  const nextStatus = (s: string) => s === 'todo' ? 'in_progress' : s === 'in_progress' ? 'done' : 'todo';

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6 font-sans">
      <header className="mb-6 border-b border-gray-800 pb-4">
        <h1 className="text-2xl font-bold text-violet-400">📋 TaskFlow</h1>
        <p className="text-xs text-gray-500 mt-0.5">Generated by KirstonAI · Task Manager</p>
      </header>

      <div className="max-w-3xl mx-auto">
        {/* Create Task */}
        <form onSubmit={createTask} className="mb-6 p-5 bg-gray-900 border border-gray-800 rounded-xl">
          <h2 className="text-sm font-semibold text-gray-300 mb-3">New Task</h2>
          {error && <div className="mb-2 p-2 bg-red-900/20 border border-red-700 text-red-400 text-xs rounded">{error}</div>}
          <div className="flex gap-2 flex-wrap">
            <input required value={form.title} onChange={e => setForm({...form, title: e.target.value})} placeholder="Task title..." className="flex-1 min-w-48 p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:border-violet-500" />
            <select value={form.priority} onChange={e => setForm({...form, priority: e.target.value})} className="p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white focus:outline-none">
              <option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option>
            </select>
            <input type="date" value={form.due_date} onChange={e => setForm({...form, due_date: e.target.value})} className="p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white focus:outline-none" />
            <input value={form.assigned_to} onChange={e => setForm({...form, assigned_to: e.target.value})} placeholder="Assigned to..." className="p-2.5 bg-gray-800 border border-gray-700 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:border-violet-500" />
            <button type="submit" className="px-5 py-2.5 bg-violet-600 hover:bg-violet-500 text-white font-semibold text-sm rounded-lg transition-colors">Add Task</button>
          </div>
        </form>

        {/* Filter */}
        <div className="flex gap-2 mb-4">
          {['all', 'todo', 'in_progress', 'done'].map(s => (
            <button key={s} onClick={() => setFilter(s)} className={`px-3 py-1.5 text-xs font-medium rounded-lg capitalize transition-colors ${filter === s ? 'bg-violet-700 text-white' : 'bg-gray-800 text-gray-400 hover:text-white'}`}>{s.replace('_', ' ')}</button>
          ))}
        </div>

        {/* Tasks */}
        {loading ? <div className="text-center text-gray-500 py-10">Loading tasks...</div>
          : tasks.length === 0 ? <div className="text-center text-gray-500 py-10">No tasks found. Create one above!</div>
          : (
          <div className="space-y-2">
            {tasks.map(t => (
              <div key={t.id} className="p-4 bg-gray-900 border border-gray-800 rounded-xl flex items-center justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <p className={`font-medium truncate ${t.status === 'done' ? 'line-through text-gray-500' : 'text-gray-100'}`}>{t.title}</p>
                  <div className="flex gap-3 mt-1 text-xs">
                    {t.assigned_to && <span className="text-gray-500">👤 {t.assigned_to}</span>}
                    {t.due_date && <span className="text-gray-500">📅 {t.due_date}</span>}
                    <span className={PRIORITY_COLORS[t.priority]}>● {t.priority}</span>
                  </div>
                </div>
                <button onClick={() => updateStatus(t.id, nextStatus(t.status))} className={`text-xs px-2.5 py-1 rounded-full border ${STATUS_COLORS[t.status]} whitespace-nowrap`}>
                  {t.status.replace('_', ' ')}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
export default App;
